export const languages: Record<string, string> = {
    ar: "العربية",
    bg: "Български",
    bn: "বাংলা",
    br: "Português (Brasil)",
    cs: "Čeština",
    da: "Dansk",
    de: "Deutsch",
    el: "Ελληνικά",
    en: "English",
    es: "Español",
    fa: "فارسی",
    fi: "Suomi",
    fr: "Français",
    he: "עברית",
    hi: "हिन्दी",
    hr: "Hrvatski",
    hu: "Magyar",
    id: "Bahasa Indonesia",
    it: "Italiano",
    ja: "日本語",
    km: "ភាសាខ្មែរ",
    ko: "한국어",
    ms: "Bahasa Melayu",
    ne: "नेपाली",
    nl: "Nederlands",
    no: "Norsk",
    pl: "Polski",
    pt: "Português (Portugal)",
    ro: "Română",
    ru: "Русский",
    sr: "Српски",
    sv: "Svenska",
    sw: "Kiswahili",
    th: "ไทย",
    tl: "Filipino",
    tr: "Türkçe",
    uk: "Українська",
    ur: "اردو",
    vi: "Tiếng Việt",
    zh: "中文"
};
